# Generated by Django 4.2 on 2024-02-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vistaprevia", "0005_auto_20240217_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
